### PR TITLE
Add example rodinia hotspot

### PR DESCRIPTION
**Pull request by jpazurikova**
Hi,
I prepared an OpenCl example, adopting the hotspot benchmark from Rodinia suite.
I am leaving for vacation tomorrow, so if there is a problem, I will deal with it after it.
Regards,
Janka

### CODE REVIEW

**Comment by Fillo7** [comment]
Hello,
thanks for the PR. Example looks good, however there are 2 things that I'd suggest to change:
1) Do not include pregenerated data files.
2) Make PR against development branch, master branch is intended for current stable release.

Regards,
Filip

**Comment by jpazurikova** [comment]
Hi,
regarding 
1. I am not sure what pregenerated data files you mean. All power_* and temp_* files are input files necessary for example to run.
2. Will do.

Regards,
Janka

**Comment by Fillo7** [comment]
Hello,

what I was thinking about regarding point 1) is if it would be possible to generate input data directly inside example code (eg. using random function), so that we don't have to rely on a single static set of data. 

However if that data set is somewhat specific (eg. computation with random input wouldn't produce result that makes sense), then it's ok to include it with PR.

Filip

**Comment by jpazurikova** [comment]
Hi,
the values in the input files depend on each other (temperature depends on the power), so random values make no sense. There is a possibility to generate them each time the example is run, but that will result in the same values. So I would prefer to include the input files as they are.
Janka

**Pull request closed without merging**
