### PR TITLE
3D convolution tunable example

### PR DESCRIPTION
**Pull request by rtrembecky**
Based on the 2D convolution from CLTune. I extended it in the third dimension and added a "Sliding plane" algorithm.

It still takes too much time to generate the tuning space due to all parameters and constraints, so it is necessary to cut it before tuning.

### CODE REVIEW

**Comment by Fillo7** [comment]
Hello,

thanks for the PR. I'll hopefully have time to review it during ths weekend. Yesterday, I commited a fix which should make generating of configurations faster, it is available on development branch.

Did you manage to try it, and if so, is there any noticable performance gain?

**Comment by rtrembecky** [comment]
I tried it, this is based on that commit. It may be working well for some simpler space, but it still doesn't get me down to minutes for the whole space.

**Comment by Fillo7** [comment]
I guess with parameter space this large, it might be better to generate configurations on-the-fly rather than all at start. This will however require some larger code modifications.

**Comment by jiri-filipovic** [comment]
Indeed this modification is not easy. It is not a high priority task now, but we can focus to solve it in the future. The ATF framework has faster tuning space generation: https://onlinelibrary.wiley.com/doi/abs/10.1002/cpe.4423, so we can also get some inspiration there.

**Pull request merged**
